name = "serverlessapigw"
main = "src/index.js"
compatibility_date = "2024-02-08"
route = { pattern = "api-test.serverlessapigw.com/*", zone_name = "serverlessapigw.com" }
logpush = false
send_metrics = true
minify = true
workers_dev = true

kv_namespaces =[
  { binding="CONFIG", id="1863fa3d004549e4800edeebeb36c0ff", preview_id = "1989f3848bb645b090f1cc82a5eb04b1"}
]

find_additional_modules = true
rules = [
    { type = "ESModule", globs = ["services/*.js","services_by_link/*.js"]}
]

[observability]
enabled = true
head_sampling_rate = 0.3
